# permissions for end users to view keepjobgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keepjobgroup-viewer-role
rules:
- apiGroups:
  - infra.keep.cn
  resources:
  - keepjobgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.keep.cn
  resources:
  - keepjobgroups/status
  verbs:
  - get
