---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - infra.keep.cn
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.keep.cn
  resources:
  - nodes/finalizers
  verbs:
  - update
- apiGroups:
  - infra.keep.cn
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
