# permissions for end users to edit virtualnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualnode-editor-role
rules:
- apiGroups:
  - infra.keep.cn
  resources:
  - virtualnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.keep.cn
  resources:
  - virtualnodes/status
  verbs:
  - get
