apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      #hostNetwork: true #设置为true时，可以通过该节点ip和端口直接访问jupyter服务
      containers:
        - name: jupyter-lab
          image: ubtcuda:9.2
          ports:
            - containerPort: 8888
          command: [ "/opt/conda/bin/jupyter" ]
          args: [ "lab" ]
---
kind: Service
apiVersion: v1
metadata:
  name: test-jupyter
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - protocol: TCP
      nodePort: 30040
      port: 8888
      targetPort: 8888