apiVersion: infra.keep.cn/v1
kind: KeepJob
metadata:
  name: keepjob-sample
spec:
  # TODO(user): Add fields here
  job_name: keep-job-test
  job_type: online_job
  namespace: default
  image: nginx
  replica: 2
  plugins: [ "service" ]
  job_queue_name: keepqueue-default

