#源镜像
#FROM golang:1.17
FROM golang:1.17
#MAINTAINER ZhangLianjun "zhanglianjun@xiaohongshu.com"
ENV TZ Asia/Shanghai

ENV GOPROXY https://goproxy.cn,direct
ENV GO111MODULE on

#工作目录作目录
WORKDIR $GOPATH/src/mock-server
ADD mock-server.tar.gz .

EXPOSE 8080

CMD ["./run/main.sh"]




